[build]
  publish = "dist/custom-element-language-copy"
  command = "npm run build:prod"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "https://manage.kontent.ai"
    X-XSS-Protection = "1; mode=block"
